services:
    bc_myd_music.artist_manager:
        class: Bc\Bundle\Myd\MusicBundle\Entity\ArtistManager
        arguments:
            - @doctrine.orm.entity_manager
            - "Bc\Bundle\Myd\MusicBundle\Entity\Artist"

    bc_myd_music.album_manager:
        class: Bc\Bundle\Myd\MusicBundle\Entity\AlbumManager
        arguments:
            - @doctrine.orm.entity_manager
            - "Bc\Bundle\Myd\MusicBundle\Entity\Album"

    bc_myd_music.track_manager:
        class: Bc\Bundle\Myd\MusicBundle\Entity\TrackManager
        arguments:
            - @doctrine.orm.entity_manager
            - "Bc\Bundle\Myd\MusicBundle\Entity\Track"

    bc_myd_music.track_play_manager:
        class: Bc\Bundle\Myd\MusicBundle\Entity\TrackPlayManager
        arguments:
            - @doctrine.orm.entity_manager
            - "Bc\Bundle\Myd\MusicBundle\Entity\TrackPlay"
