parameters:
#    bc_last_fm_service.example.class: Bc\Bundle\LastFmServiceBundle\Example

services:
    bc_last_fm_service.client_factory:
        class: Bc\Bundle\LastFmServiceBundle\LastFmClient
    bc_last_fm_service.client:
        class: Bc\Bundle\LastFmServiceBundle\LastFmClient
        factory_service: bc_last_fm_service.client_factory
        factory_method: factory
        arguments:
            - { api_key: 321c12389cc476b92c3a216024b363cd }
