parameters:
#    bc_last_fm_service.example.class: Bc\Bundle\LastFmServiceBundle\Example

services:
    bc_lastfm.client_factory:
        class: Bc\Bundle\LastfmBundle\Client
    bc_lastfm.client:
        class: Bc\Bundle\LastfmBundle\Client
        factory_service: bc_lastfm.client_factory
        factory_method: factory
        arguments:
            - { api_key: 321c12389cc476b92c3a216024b363cd }
