services:
    bc_myd_lastfm.import.recent_tracks:
        class: Bc\Bundle\Myd\LastFmBundle\Import\RecentTracksImporter
        arguments:
            - @bc_lastfm.client
            - @bc_myd_lastfm.artist_manager
            - @bc_myd_lastfm.album_manager
            - @bc_myd_lastfm.track_manager
